"""empty message

Revision ID: dba7337b9d89
Revises: 63b60f0dc403
Create Date: 2024-07-21 22:52:19.872119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba7337b9d89'
down_revision = '63b60f0dc403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_parcel_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_parcel_association',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parcel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='order_parcel_association_order_id_fkey'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name='order_parcel_association_parcel_id_fkey')
    )
    # ### end Alembic commands ###
